services:
  db:
    image: postgis/postgis:16-3.4
    container_name: etl_postgis
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-gis}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgis_data:/var/lib/postgresql/data
      - ./sql/enable_postgis.sql:/docker-entrypoint-initdb.d/01-enable-postgis.sql:ro
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/02-schema.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-gis}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

volumes:
  postgis_data:
    driver: local